apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginix-deploy
  name: nginix-deploy
  namespace: champ
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginix-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginix-deploy
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
