apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
  namespace: champ
spec:
  tolerations:
    - key: "techie"
      operator: "Equal"
      value: "champ"
      effect: "NoSchedule"
  containers:
  - image: nginx
    name: nginx
    resources:
      requests:
        memory: 20Mi
      limits:
        memory: 50Mi
    env:
    - name: name
      value: champ
    - name: app-name
      valueFrom:
        configMapKeyRef:
          name: webapp-config-map
          key: APP_NAME
    volumeMounts:
    - name: cm-volume
      mountPath: "/config"
      readOnly: true
    securityContext:
      runAsUser: 1001
      capabilities:
        add : ["SYS_TIME"]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name : cm-volume
      configMap:
        name: webapp-config-map
status: {}
