apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
  namespace: champ
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
    env:
    - name: name
      value: champ

  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
